os:
- linux
language: go
go:
- 1.13.x
env:
  global:
  - GO111MODULE=on
sudo: required
dist: bionic
cache:
  directories:
  - "$HOME/gopath/pkg/mod"
if: branch in (master, develop)
before_install:
- git clone -b v0.59.1 https://github.com/gohugoio/hugo.git
- cd hugo
- go install --tags extended
- hugo env
jobs:
  include:
  - if: branch = develop
    install: true
    script:
    - cd $TRAVIS_BUILD_DIR
    - hugo --environment staging
    - echo "docs.stg.ptah.pro" > ./public/CNAME
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      target-branch: master
      verbose: true
      repo: protocolone/ptah-docs-stage
      fqdn: docs.stg.ptah.pro
      local-dir: "./public"
      on:
        branch: develop
  - if: branch = master
    install: true
    script:
    - cd $TRAVIS_BUILD_DIR
    - hugo --environment production
    - echo "docs.ptah.pro" > ./public/CNAME
    deploy:
    - provider: pages
      skip-cleanup: true
      github-token: "$GITHUB_TOKEN"
      keep-history: true
      target-branch: gh-pages
      verbose: true
      repo: protocolone/ptah-docs
      fqdn: docs.ptah.pro
      local-dir: "./public"
      on:
        branch: master
notifications:
  slack:
    secure: 5clmRtRDy7m5OoHw3FNhKpR2Lhga0AF0LvMwvTAKG/CPBTdBubK3D31MbwQwAUeetKkqFyFepbRY1lfNK7VL0aTD8r0HtE47aUZdCNVr+5DnxsMf7dit3nYmXIN0rXsAOWZ5Wa1yUKxhxI5B71WNWPbcJOTOAwbsIiOAn4blHhvug6qwfs+/ysC+BJQgAOhl/+PYrlhPgpEKIc97wCDyEtkHwwl7igWsL3TlLkZEXXfY8140OW21n4tWNZdhpmhb8jcHQE+IrYldQ8ZPZDFI2HVS54WpGxkfuLc5bsxaQI6iCjkMffUsPe+uFRUdtU92Ly1EGKPZOOng93T125s2rC1Jj7p9arofNWnktDFkY0roZqpIYRX9dX2NnyXUl7FDIAI5bHnq2E/B8ffJqc9x7JKjNKW3qRAETAg67TZ5WFAdpp5yhA45TH5zAdrP9/j4qBzw1RQ47yQIIw9C4vUuL39FY9/YPCWEA5zGAHozGGE1j3qjqs2Ez+wwGnH8Yq22XzD9uvnrAZNOcMGK6F4vKX+6Ue2+9MmYeQp5ohWIpWQFKL4V8g+9+m2fRNEA7vmZ4pjP7OIv1H0oVJVHos/hxymZZ/ng2veiXKFclvklDBQLb/iVP1z5daz65g7bIzKQYHa6iceuBVkXnTcnv8DLDiLeE3XQCWf/7itdXXmzcqE=
